[package]
name = "marvin32-rs"
version = "0.1.0"
authors = ["Damian Gryski <damian@gryski.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.2"
